/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;

/**
 *
 * @author acer e1
 */
public class GlavnaForma extends javax.swing.JFrame {

    Korisnik ulogovaniKorisnik;

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma(Korisnik ulogovaniKorisnik) {
        initComponents();
        this.ulogovaniKorisnik = ulogovaniKorisnik;
        lblUlogovaniKorisnik.setText("Ulogovani korisnk " + ulogovaniKorisnik);

    }

    public Korisnik getUlogovaniKorisnik() {
        return ulogovaniKorisnik;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovaniKorisnik = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiPrvaGrupa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Ispita");

        jmiPrvaGrupa.setText("PrvaGrupa");
        jmiPrvaGrupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrvaGrupaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiPrvaGrupa);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblUlogovaniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblUlogovaniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPrvaGrupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrvaGrupaActionPerformed
        
        UnosOsiguranja uo = new UnosOsiguranja(this, true);
        uo.pack();
        uo.setVisible(true);
        
        
    }//GEN-LAST:event_jmiPrvaGrupaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiPrvaGrupa;
    private javax.swing.JLabel lblUlogovaniKorisnik;
    // End of variables declaration//GEN-END:variables
}
