/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;
import domen.Osiguranje;
import domen.Vozilo;
import domen.VrstaOsiguranja;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logika.Kontroler;
import model.ModelTabeleOsiguranja;
import model.ModelTabeleVrsta;

/**
 *
 * @author acer e1
 */
public class UnosOsiguranja extends javax.swing.JDialog {

    /**
     * Creates new form UnosOsiguranja
     */
    public UnosOsiguranja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediTabeluOsiguranja();
        popuniVozila();
        popuniPodatkeVozila();
        popuniVrsteOsiguranja();
        popuniPodatkeVrstaOsiguranja();
        srediTabeluVrstaOsigranja();

        popuniPodatkeTabeleOsiguranja();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        cmbVrsteOsiguranja = new javax.swing.JComboBox();
        cmbVozilo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtVlasnikVozila = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGodinaProizvodnje = new javax.swing.JTextField();
        txtCenaVrste = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaOsiguranja = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaVrstaOsiguranja = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Datum osiguranja");

        jLabel2.setText("Vozilo");

        jLabel3.setText("Vrsta osiguranja");

        cmbVrsteOsiguranja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbVrsteOsiguranja.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVrsteOsiguranjaItemStateChanged(evt);
            }
        });

        cmbVozilo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbVozilo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVoziloItemStateChanged(evt);
            }
        });

        jLabel4.setText("Vlasnik vozila");

        txtVlasnikVozila.setEnabled(false);

        jLabel5.setText("Godina proizvodnje");

        txtGodinaProizvodnje.setEnabled(false);

        txtCenaVrste.setEnabled(false);

        jLabel6.setText("Cena vrste osiguranja");

        tabelaOsiguranja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaOsiguranja);

        tabelaVrstaOsiguranja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaVrstaOsiguranja);

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbVrsteOsiguranja, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addComponent(txtCenaVrste, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDatum)
                                    .addComponent(cmbVozilo, 0, 232, Short.MAX_VALUE))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtVlasnikVozila, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(29, 29, 29)
                                        .addComponent(txtGodinaProizvodnje, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btnDodaj)
                        .addGap(44, 44, 44)
                        .addComponent(btnObrisi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtVlasnikVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGodinaProizvodnje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbVrsteOsiguranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCenaVrste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvaj)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbVoziloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVoziloItemStateChanged
        popuniPodatkeVozila();
        popuniPodatkeTabeleOsiguranja();
    }//GEN-LAST:event_cmbVoziloItemStateChanged

    private void cmbVrsteOsiguranjaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVrsteOsiguranjaItemStateChanged
        popuniPodatkeVrstaOsiguranja();        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVrsteOsiguranjaItemStateChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        VrstaOsiguranja vs = (VrstaOsiguranja) cmbVrsteOsiguranja.getSelectedItem();
        ModelTabeleVrsta mtv = (ModelTabeleVrsta) tabelaVrstaOsiguranja.getModel();
        mtv.dodaj(vs);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int red = tabelaVrstaOsiguranja.getSelectedRow();
        if (red != -1) {
            ModelTabeleVrsta mtv = (ModelTabeleVrsta) tabelaVrstaOsiguranja.getModel();
            mtv.obrisi(red);
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        String dat = txtDatum.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        try {
            Date datum = sdf.parse(dat);
            Vozilo v = (Vozilo) cmbVozilo.getSelectedItem();

            ArrayList<Osiguranje> listaOsiguranja = Kontroler.getInstanca().vratiOsiguranja(v);
            for (Osiguranje osiguranje : listaOsiguranja) {
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(osiguranje.getDatumPocetka());
                int godinaPocetka = calendar.get(Calendar.YEAR);

                Calendar cal = Calendar.getInstance();
                cal.setTime(datum);
                int brojGodina = cal.get(Calendar.YEAR);

                if (brojGodina == godinaPocetka) {
                    JOptionPane.showMessageDialog(this, "Godina pocetka osiguranja");
                    return;
                }
            }

            // trenutna godina
            int god = Calendar.getInstance().get(Calendar.YEAR);
            int razlika = god - v.getGodinaProzivodnje();

            ModelTabeleVrsta tvs = (ModelTabeleVrsta) tabelaVrstaOsiguranja.getModel();
            ArrayList<VrstaOsiguranja> vrste = tvs.getVrste();
            double premija = 0;
            for (VrstaOsiguranja vrstaOsiguranja : vrste) {
                premija += razlika * vrstaOsiguranja.getCena();
            }
            Korisnik ulogovaniKorisnik = ((GlavnaForma) getParent()).getUlogovaniKorisnik();

            Osiguranje o = new Osiguranje(-1, v, datum, new Date(), ulogovaniKorisnik.getImePrezime(), premija);
            boolean uspesno = Kontroler.getInstanca().sacuvajOSiguranje(o);
            if (uspesno) {
                JOptionPane.showMessageDialog(this, "Uspesno sacuvano u bazi");
            } else {
                JOptionPane.showMessageDialog(this, "Nije sacuvano");
            }
        } catch (ParseException ex) {
            Logger.getLogger(UnosOsiguranja.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Datum je u losem pogresnom formatu");
        }


    }//GEN-LAST:event_btnSacuvajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbVozilo;
    private javax.swing.JComboBox cmbVrsteOsiguranja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaOsiguranja;
    private javax.swing.JTable tabelaVrstaOsiguranja;
    private javax.swing.JTextField txtCenaVrste;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtGodinaProizvodnje;
    private javax.swing.JTextField txtVlasnikVozila;
    // End of variables declaration//GEN-END:variables

    private void popuniVozila() {
        cmbVozilo.removeAllItems();
        ArrayList<Vozilo> lista = Kontroler.getInstanca().vratiListuVozila();

        for (Vozilo vozilo : lista) {
            cmbVozilo.addItem(vozilo);
        }
    }

    private void popuniPodatkeVozila() {
        Vozilo vozilo = (Vozilo) cmbVozilo.getSelectedItem();
        if (vozilo != null) {
            txtGodinaProizvodnje.setText(vozilo.getGodinaProzivodnje() + "");
            txtVlasnikVozila.setText(vozilo.getIme() + " " + vozilo.getPrezime());
        }
    }

    private void popuniVrsteOsiguranja() {
        cmbVrsteOsiguranja.removeAllItems();
        ArrayList<VrstaOsiguranja> lista = Kontroler.getInstanca().getListaVrsteOsiguranja();

        for (VrstaOsiguranja vrstaOsiguranja : lista) {
            cmbVrsteOsiguranja.addItem(vrstaOsiguranja);
        }
    }

    private void popuniPodatkeVrstaOsiguranja() {
        VrstaOsiguranja vs = (VrstaOsiguranja) cmbVrsteOsiguranja.getSelectedItem();
        if (vs != null) {
            txtCenaVrste.setText(vs.getCena() + "");
        }
    }

    private void srediTabeluVrstaOsigranja() {
        ModelTabeleVrsta mtv = new ModelTabeleVrsta();
        tabelaVrstaOsiguranja.setModel(mtv);

    }

    private void srediTabeluOsiguranja() {
        ModelTabeleOsiguranja mto = new ModelTabeleOsiguranja();
        tabelaOsiguranja.setModel(mto);
    }

    private void popuniPodatkeTabeleOsiguranja() {
        Vozilo vozilo = (Vozilo) cmbVozilo.getSelectedItem();
        if (vozilo != null) {
            ArrayList<Osiguranje> listaOsiguranja = Kontroler.getInstanca().vratiOsiguranja(vozilo);
            ModelTabeleOsiguranja mto = (ModelTabeleOsiguranja) tabelaOsiguranja.getModel();
            mto.setLista(listaOsiguranja);
        }
    }

}
